### ISSUE TITLE
Change default behaviour of `odir`

### ISSUE THREAD

**Issue by sixy6e** [GeoscienceAustralia/sun-glint-correction#16]
The default behaviour of the `odir` keyword is to create sub-directories within the actual packaged directory space.  This is undesirable for data that would be hosted as production and consumer-ready.  i.e. a live space where any user can be updating, or downloading data from.

Ideally, we need to create a temporary directory space to write any intermediates and cleans up when finished.  If the user doesn't supply an output directory we shouldn't be returning files to them, nor outputting them into a global space.

[Headley](https://github.com/GeoscienceAustralia/sun-glint-correction/blob/develop/sungc/deglint.py#L810) example.

[Behaviour](https://github.com/GeoscienceAustralia/sun-glint-correction/blob/develop/sungc/deglint.py#L895) within the Headley method.

**Comment by Oceancolour-RG** [comment]
This issue was resolve in PR#17
